// Spider-Man pixel art. '.' = transparent, 'R' = suit red, 'B' = suit blue,
// 'W' = eye white, 'o' = spider-tracer.

const parse = (s) => s.trim().split('\n').map((r) => r.trim());

// 12x14, right-facing, one arm raised to the web line. The web attaches at
// WEB_ANCHOR below, which is the raised hand.
export const SWING_REACH = parse(`
....R.......
....R.......
...RRR......
..RRRRR.....
..WWRWW.....
..RRRRR.....
...RRR......
..RRRRR..R..
..RRRRR.....
..RRRRR.....
...BBB......
..BB.BB.....
.BB...BB....
.B.....B....
`);

// Legs tucked for the fast part of the arc.
export const SWING_TUCK = parse(`
....R.......
....R.......
...RRR......
..RRRRR.....
..WWRWW.....
..RRRRR.....
...RRR......
..RRRRR..R..
..RRRRR.....
..RRRRR.....
...BBB......
..BBBBB.....
..BB.BB.....
...B..B.....
`);

export const SPIDEY_W = 12;
export const SPIDEY_H = 14;

// Offset of the raised hand within the sprite - where the web line starts.
export const WEB_ANCHOR = { x: 4, y: 0 };
