// Pixel sprites. '.' = transparent, '#' = body, '+' = accent, 'o' = coin, '*' = spark.

const parse = (s) => s.trim().split('\n').map((r) => r.trim());

// 12x16 runner, facing right. Arms sit in the accent colour so the stride
// stays readable at this size.
export const RUNNER_RUN_A = parse(`
...######...
...######...
...######...
...######...
...######...
....####....
.++######++.
.++######++.
...######...
...######...
...######...
...##..##...
...#....#...
..##....##..
..#......#..
..#......#..
`);

export const RUNNER_RUN_B = parse(`
...######...
...######...
...######...
...######...
...######...
....####....
...######++.
...######...
.++######...
...######...
...######...
....####....
....#..#....
...##..##...
...#....#...
...#....#...
`);

export const RUNNER_JUMP = parse(`
...######...
...######...
...######...
...######...
...######...
....####....
++.######.++
.++######++.
...######...
...######...
...######...
...##..##...
..##....##..
..#......#..
............
............
`);

export const RUNNER_W = 12;
export const RUNNER_H = 16;

// 7x7 collectible sitting above each week column.
export const COIN = parse(`
...o...
..ooo..
.ooooo.
ooooooo
.ooooo.
..ooo..
...o...
`);

// 7x7 pickup burst, drawn for a single frame where the coin was.
export const BURST = parse(`
*.....*
.......
.......
...*...
.......
.......
*.....*
`);
